set (DirectX_ROOT_DIR "${CMAKE_CURRENT_LIST_DIR}" CACHE PATH "" FORCE)

# DirectX 7
if (CMAKE_GENERATOR_TOOLSET MATCHES "_xp$")
    set (DirectX_D3D_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/Include" CACHE PATH "" FORCE)
endif ()
