set (DirectX_ROOT_DIR "${CMAKE_CURRENT_LIST_DIR}" CACHE PATH "" FORCE)

# DirectX 7
set (DirectX_D3D_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/Include" CACHE PATH "" FORCE)
set (DirectX_D3DX_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/Include" CACHE PATH "" FORCE)
set (DirectX_D3DX_LIBRARY "${CMAKE_CURRENT_LIST_DIR}/Lib/d3dx.lib" CACHE FILEPATH "" FORCE)

# DirectX 8
set (DirectX_D3D8_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/Include" CACHE PATH "" FORCE)
set (DirectX_D3D8_LIBRARY "${CMAKE_CURRENT_LIST_DIR}/Lib/x86/d3d8.lib" CACHE FILEPATH "" FORCE)
set (DirectX_D3DX8_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/Include" CACHE PATH "" FORCE)
set (DirectX_D3DX8_LIBRARY "${CMAKE_CURRENT_LIST_DIR}/Lib/d3dx8.lib" CACHE FILEPATH "" FORCE)
